import type { Metadata } from "next";
import { DM_Sans, Playfair_Display } from "next/font/google";
import StoreProvider from "../StoreProvider";
import "../globals.css";
import Container from "@/shared/components/Container";
import { Toaster } from "react-hot-toast";

const dmSANS = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${dmSANS.variable} ${playfairDisplay.variable}  antialiased`}
      lang="en"
    >
      <body>
        <Container>
          <StoreProvider>
            <Toaster
              position="bottom-center" // Đặt toaster ở giữa dưới
              toastOptions={{
                className: `
            !bg-black 
            !text-white 
            !rounded-full 
            !text-[14px]
            !max-w-[800px]
       `,
              }}
            />

            {children}
          </StoreProvider>
        </Container>
      </body>
    </html>
  );
}
