import type { Metadata } from "next";
import { DM_Sans, Playfair_Display } from "next/font/google";
import StoreProvider from "../StoreProvider";
import "../globals.css";
import Header from "@/shared/components/Header/Header";
import Container from "@/shared/components/Container";

const dmSANS = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${dmSANS.variable} ${playfairDisplay.variable}  antialiased`}
      lang="en"
    >
      <body>
        <Container>
          <Header />
          <StoreProvider>{children}</StoreProvider>
        </Container>
      </body>
    </html>
  );
}
